"""init: users and trip_records tables

Revision ID: a433f57d0acb
Revises: 
Create Date: 2026-08-26 10:02:50.203819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a433f57d0acb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=16), nullable=False),
    sa.Column('travel_days', sa.Integer(), nullable=False),
    sa.Column('transportation', sa.String(length=32), nullable=False),
    sa.Column('accommodation', sa.String(length=32), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=False),
    sa.Column('free_text_input', sa.Text(), nullable=False),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_records_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_records_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('trip_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_trip_records_city'))

    op.drop_table('trip_records')
    # ### end Alembic commands ###
