<template><main class="page"><a-card class="glass-card card" :bordered="false"><header><a-button @click="router.push('/')">← 首页</a-button><div><h1>智能旅行助手</h1><p>Agent 只生成草稿，Java 校验并由你确认后保存。</p></div><a-tag :color="cap?.agent==='available'?'green':'red'">Agent {{cap?.agent||'检查中'}}</a-tag></header>
  <a-select v-model:value="mode" style="width:180px"><a-select-option value="help">使用帮助</a-select-option><a-select-option value="research">攻略问答</a-select-option><a-select-option value="plan">创建行程</a-select-option><a-select-option value="revise">修改行程</a-select-option></a-select>
  <a-input v-if="mode==='research'||mode==='plan'" v-model:value="city" placeholder="城市" style="width:160px;margin-left:8px"/>
  <a-space v-if="mode==='plan'" class="fields"><input type="date" v-model="start"/><input type="date" v-model="end"/></a-space>
  <a-space v-if="mode==='revise'" class="fields"><a-input-number v-model:value="recordId" placeholder="行程ID"/><a-input-number v-model:value="version" :min="1"/><a-input-number v-model:value="dayIndex" :min="0"/></a-space>
  <a-textarea v-model:value="content" :rows="4" placeholder="告诉助手你的问题或修改要求" class="message"/><a-button type="primary" :loading="sending" @click="send">发送</a-button>
  <a-alert v-if="reply" :type="replyType" :message="reply" show-icon class="reply"/><a-button v-if="taskId" @click="router.push('/tasks')">查看任务 {{taskId}}</a-button>
</a-card></main></template>
<script setup lang="ts">import{ref,onMounted}from'vue';import{useRouter}from'vue-router';import{createAssistantConversation,sendAssistantMessage,fetchCapabilities}from'@/services/api';const router=useRouter(),conversation=ref(''),mode=ref('help'),content=ref(''),city=ref('北京'),start=ref(''),end=ref(''),recordId=ref<number>(),version=ref(1),dayIndex=ref(0),reply=ref(''),replyType=ref<'success'|'error'>('success'),taskId=ref(''),sending=ref(false),cap=ref<any>();onMounted(async()=>{cap.value=await fetchCapabilities();conversation.value=(await createAssistantConversation()).id});async function send(){sending.value=true;reply.value='';try{const payload:any={mode:mode.value,content:content.value,city:city.value};if(mode.value==='plan'){const days=Math.floor((new Date(end.value).getTime()-new Date(start.value).getTime())/86400000)+1;payload.trip_request={city:city.value,start_date:start.value,end_date:end.value,travel_days:days,transportation:'公共交通',accommodation:'经济型酒店',preferences:[],free_text_input:content.value,constraints:{must_visit:[],avoid:[],daily_minutes:600,max_inter_stop_walking_km:null}}}if(mode.value==='revise')Object.assign(payload,{record_id:recordId.value,version:version.value,day_index:dayIndex.value});const r=await sendAssistantMessage(conversation.value,payload);taskId.value=r.task_id||'';reply.value=r.message||r.data?.status||'已创建智能任务';replyType.value='success'}catch(e:any){reply.value=e?.response?.data?.message||'助手暂不可用';replyType.value='error'}finally{sending.value=false}}
</script>
<style scoped>.page{padding:36px;min-height:100vh}.card{max-width:820px;margin:auto;border-radius:22px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.fields{margin:12px}.message{margin:18px 0}.reply{margin:18px 0}@media(max-width:700px){.page{padding:12px}header{align-items:flex-start;flex-direction:column}}</style>
