<template><main class="page"><a-card class="glass-card card" :bordered="false">
  <header><a-button @click="router.push('/favorites')">← 收藏</a-button><h1>创建手工行程</h1><a-button type="primary" :loading="saving" @click="save">校验并保存</a-button></header>
  <a-row :gutter="12"><a-col :span="6"><a-input v-model:value="form.title" placeholder="行程标题"/></a-col><a-col :span="4"><a-input v-model:value="form.city" placeholder="城市"/></a-col><a-col :span="5"><input type="date" v-model="form.start_date" class="date"/></a-col><a-col :span="5"><input type="date" v-model="form.end_date" class="date"/></a-col><a-col :span="4"><a-select v-model:value="form.transportation" style="width:100%"><a-select-option value="公共交通">公共交通</a-select-option><a-select-option value="自驾">自驾</a-select-option><a-select-option value="步行">步行</a-select-option></a-select></a-col></a-row>
  <a-alert v-if="error" type="error" :message="error" show-icon class="gap"/>
  <section class="pool"><h3>收藏池</h3><a-tag v-for="poi in unassigned" :key="poi.poi_id" color="purple">{{poi.name}} <a @click="assign(poi,0)">加入第1天</a></a-tag></section>
  <div class="days"><a-card v-for="(day,index) in days" :key="index" :title="`第 ${index+1} 天`" class="day">
    <a-empty v-if="!day.length" description="暂无景点"/><div v-for="(poi,pos) in day" :key="poi.poi_id" class="stop"><strong>{{poi.name}}</strong><a-space>
      <a-button size="small" :disabled="pos===0" @click="moveOrder(index,pos,-1)">↑</a-button><a-button size="small" :disabled="pos===day.length-1" @click="moveOrder(index,pos,1)">↓</a-button>
      <a-button size="small" :disabled="index===0" @click="moveDay(index,pos,index-1)">前一天</a-button><a-button size="small" :disabled="index===days.length-1" @click="moveDay(index,pos,index+1)">后一天</a-button><a-button size="small" danger @click="remove(index,pos)">移除</a-button>
    </a-space></div></a-card></div>
  <p class="note">景点事实和路线由 Java 高德 REST 重新查询；无法核验的内容会保存为待处理草稿。</p>
</a-card></main></template>
<script setup lang="ts">import{computed,reactive,ref,watch}from'vue';import{useRouter}from'vue-router';import{message}from'ant-design-vue';import{createManualTrip,storeTripResult}from'@/services/api'
const router=useRouter(),saving=ref(false),error=ref('');const pool=ref<any[]>(JSON.parse(sessionStorage.getItem('manualFavoritePois')||'[]'));const days=ref<any[][]>([[]]);
const form=reactive({title:'我的手工行程',city:pool.value[0]?.city||'北京',start_date:'',end_date:'',transportation:'公共交通',accommodation:'经济型酒店'})
const unassigned=computed(()=>pool.value.filter(p=>!days.value.some(d=>d.some(x=>x.poi_id===p.poi_id))))
watch(()=>[form.start_date,form.end_date],()=>{if(!form.start_date||!form.end_date)return;const n=Math.floor((new Date(form.end_date).getTime()-new Date(form.start_date).getTime())/86400000)+1;if(n<1||n>30){error.value='日期范围必须为1到30天';return}error.value='';const next=Array.from({length:n},(_,i)=>days.value[i]||[]);days.value.slice(n).flat().forEach(p=>next[n-1].push(p));days.value=next})
function assign(p:any,d:number){if(days.value.length)days.value[d].push(p)}function remove(d:number,p:number){days.value[d].splice(p,1)}function moveOrder(d:number,p:number,delta:number){const a=days.value[d];[a[p],a[p+delta]]=[a[p+delta],a[p]]}function moveDay(d:number,p:number,target:number){days.value[target].push(days.value[d].splice(p,1)[0])}
async function save(){if(!form.start_date||!form.end_date){error.value='请选择日期';return}saving.value=true;try{const response=await createManualTrip({...form,travel_days:days.value.length,preferences:[],free_text_input:'',constraints:{must_visit:[],avoid:[],daily_minutes:600,max_inter_stop_walking_km:null},days:days.value.map(d=>({poi_ids:d.map(p=>p.poi_id)}))});storeTripResult(response);message.success(response.quality?.outcome==='draft'?'已保存待核验草稿':'手工行程已保存');router.push('/result')}catch(e:any){error.value=e?.response?.data?.message||'保存失败'}finally{saving.value=false}}
</script><style scoped>.page{padding:36px;min-height:100vh}.card{max-width:1200px;margin:auto;border-radius:22px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.date{width:100%;height:32px;border:1px solid #d9d9d9;border-radius:6px;padding:0 8px}.gap{margin:16px 0}.pool{padding:16px;background:#f7f5ff;border-radius:12px;margin:20px 0}.days{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:16px}.day{min-height:220px}.stop{padding:10px 0;border-bottom:1px solid #eee;display:flex;justify-content:space-between;gap:8px}.note{margin-top:18px;color:#667085}@media(max-width:700px){.page{padding:12px}header,.stop{align-items:flex-start;flex-direction:column}}</style>
